### ISSUE TITLE
Exchange loki-stack with loki helm chart, due to deprecation of loki-stack

### ISSUE THREAD

**Issue by janaurka** [adfinis/helm-charts#1058]
So, in `infra-logging` we are using [`loki-stack`](https://github.com/adfinis/helm-charts/blob/main/charts/logging-apps/values.yaml#L12-L14) as helm chart. This is [deprecated and should not be used anymore](https://community.grafana.com/t/difference-between-helm-charts-loki-and-loki-stack/87380). 

The new chart to use is [`loki`](https://github.com/grafana/loki/tree/main/production/helm/loki).

This only deploys `loki` and not `promtail` and `grafana`, so we should also add the `promtail` helm chart (and maybe [`vector`](https://vector.dev/docs/reference/configuration/sinks/loki/) -> the thing used by RedHat for OpenShift to ship logs to loki) to re-add the functionality loss we have from going `loki-stack` -> `loki`. 

Also it seems we don’t have a `grafana` support atm. We also need that, since `loki-stack` gave us that, but i overall like it way more as a standalone in `infra-apps` anyways.

**Comment by janaurka** [comment]
https://grafana.com/blog/2022/12/19/the-only-helm-chart-you-need-for-grafana-loki-is-here/ more info

**Comment by eyenx** [comment]
Integrating loki into grafana can be achieved over kubePrometheusStack and grafana.additionalDatasources.

**Comment by tongpu** [comment]
I think the bare minimum functionality we should provide is combining the loki chart with the promtail chart. This should be rather easy, because the defaults of the promtail chart are very well suited to work with the loki chart and by combining them in the infra-logging chart as the two default options we should be well suited to replace our current deployment based on loki-stack.

Regarding Vector, I had a discussion with @vmaillot to replace a beats deployment at a customer with vector, so adding it to infra-logging is probably a good idea, but we need to evaluate if it is a good idea to make it the default over promtail and I would base that decision partially on resource consumption. It drives me crazy to see a simple component like promtail consume 100-300 MiB of memory and if Vector would be significantly better, we could discuss if it is better suited as an alternative. I expect that Vector would require a lot more configuration then a typical promtail setup, so I wouldn't consider it our first choice.

**Comment by hairmare** [comment]
so, my understanding is that it's probably best to 
1. add loki and promtail to logging-apps
2. mark loki-stack as deprecated following our deprecation policy for -apps

i didn't :100: catch if there is an obvious distinction between loki-distributed (microservice mode) and the regular loki chart, but it feels like the distinction isn't too relevant (and i'd probably tend towards microservices, but that's just me thinking the word is more fancy).

**Comment by tongpu** [comment]
[`loki-distributed`](https://github.com/grafana/helm-charts/tree/4f0b5dfba9d7cf519e39f84c8e5c74f3da79b5b4/charts/loki-distributed) is a community maintained Helm chart for running Loki in microservices mode. The recommended chart for deploying Loki, which is maintained by Grafana and the community, is [`loki`](https://github.com/grafana/loki/tree/e3b7bcb67d437e0e77b4dc16d8515af992d0f4d5/production/helm/loki) in grafana/loki, which defaults to distributed, but can be configured to run in single binary mode.

**Comment by hairmare** [comment]
> [`loki-distributed`](https://github.com/grafana/helm-charts/tree/4f0b5dfba9d7cf519e39f84c8e5c74f3da79b5b4/charts/loki-distributed) is a community maintained Helm chart for running Loki in microservices mode. The recommended chart for deploying Loki, which is maintained by Grafana and the community, is [`loki`](https://github.com/grafana/loki/tree/e3b7bcb67d437e0e77b4dc16d8515af992d0f4d5/production/helm/loki) in grafana/loki, which defaults to distributed, but can be configured to run in single binary mode.

I'm not sure i understand you, are you ok with my proposed changes from https://github.com/adfinis/helm-charts/issues/1058#issuecomment-1671492831? You're confirming that we should stick with `loki` instead of considering `loki-distributed` , right?

**Comment by tongpu** [comment]
> I'm not sure i understand you, are you ok with my proposed changes from [#1058 (comment)](https://github.com/adfinis/helm-charts/issues/1058#issuecomment-1671492831)? You're confirming that we should stick with `loki` instead of considering `loki-distributed` , right?

Yes, my comment was primarily meant to extend the statement from @janaurka.
